# Generated by Django 4.2.4 on 2023-08-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_subscription_options_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='test_id', max_length=100, verbose_name='payment_id'),
            preserve_default=False,
        ),
    ]
