# Generated by Django 4.2.4 on 2023-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='payment_id'),
        ),
    ]
