# Generated by Django 4.2.4 on 2023-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated_time'),
        ),
    ]
